spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aitovoice_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
  jpa:
    show-sql: true

logging:
  level:
    com.aitovoice: DEBUG
